### ISSUE TITLE
importing arbitrary methods causes unexpected errors

### ISSUE THREAD

**Issue by fursich** [QWYNG/pry-singular#1]
Hi, thanks for the inspiring gems!

I played around it a bit and occasionally encountered a behavior as below  - which I found slightly surprising :(

1. setting it up as suggested:

```ruby
> class Foo
>   def self.foo # whatever method(s) you'd want to define
>     puts 'foo'
>   end
> end
>
> PrySingular.set_class Foo
```

2. then you happen to (let's say) re-open the class and define another method..

```ruby
[4] pry(main)> class Foo
NameError: undefined local variable or method `classFoo' for Foo:Class
Did you mean?  class
from (eval):1:in `block (3 levels) in import_class_command'
```

### quick analysis

Looks like it is coming from the feature that the gem re-defines [ALL the class methods inherited from its ancestors](https://github.com/QWYNG/pry-singular/blob/fdcea249d542db6319b3f68297565cac78af43cb/lib/pry-singular.rb#L14), which (naturally) has some core Ruby methods within Object / BasicObject.

### ideas

Got a few ideas for this issue (hoping these make sense)

- can we import *methods defined on the direct class (Foo in this case)*, or at least (if that screws up all the methods from included modules) can we import the methods from the ancestors, up to *one class before Object class comes in*? 

- Or, if I dare one step further, would you think you can add an interface that allows us to *selectively* import the specific methods (just like Python's import command does, for instance)

Happy to contribute PR if needed, but let me know what you think.
Thanks once again and hope you keep going with this cool gem 👍

**Comment by QWYNG** [comment]
@fursich 
Thank you for the issue.
Certainly, Gem generates of all ancestors method commands now.
I think need to create import the specific methods too.
But I can not imagine the code that works like the one below
>can we import methods defined on the direct class (Foo in this case), or at least (if that screws up all the methods from included modules) can we import the methods from the ancestors, up to one class before Object class comes in?

Could you create PR with code that can be implemented?
Aside, I will do this
> like Python's import command does, for instance

Thanks once again!

**Comment by fursich** [comment]
@QWYNG thanks a lot for your swift feedback!

>> can we import methods defined on the direct class (Foo in this case), or at least (if that screws up all the methods from included modules) can we import the methods from the ancestors, up to one class before Object class comes in?

>? Could you create PR with code that can be implemented?

Will submit proposal then 👍 

Also that would be really exciting if `set_class` method provides python-like interface. That would allow us to whitelist only "importable" methods, making the gem even greater..! :))

**Comment by fursich** [comment]
(closing the issue as the corresponding PR above has been merged)
